Update _location.py
sanders41/weather-command pull request #414
Opened 2023-04-16 13:37 UTC by Himanshuch1708

The changes include:

- Generating a cache key based on the URL using hashlib.sha256().
- Checking the cache using the cache key instead of the city_zip parameter if how is "zip."
- Adding the Location object to the cache using the cache key instead of the city_zip parameter.

I hope this helps!

2023-04-16 18:16 UTC, sanders41 commented
I have had a chance to go through this and it will take some significant updates to work. Everything can be done by using the location url as the cache key, and the zip can be dropped. The cache class needs to be updated to handle this, then each of the places that uses cache needs to be update. In addition the test suite needs to be updated to handle the changes.

Also, I did some bench marking with the cache key. Because it doesn't need to be url safe ~400 ms can be saved by not hashing it and just storing it as a raw string so that part can be dropped.

If you are up for making all the changes I can add some more detail on what needs to be done. If it sounds like too much I understand also.

2023-04-16 18:58 UTC, Himanshuch1708 commented
> I have had a chance to go through this and it will take some significant updates to work. Everything can be done by using the location url as the cache key, and the zip can be dropped. The cache class needs to be updated to handle this, then each of the places that uses cache needs to be update. In addition the test suite needs to be updated to handle the changes.
> 
> Also, I did some bench marking with the cache key. Because it doesn't need to be url safe ~400 ms can be saved by not hashing it and just storing it as a raw string so that part can be dropped.
> 
> If you are up for making all the changes I can add some more detail on what needs to be done. If it sounds like too much I understand also.

I would like to give it a try since I am interested in working on a good project and want to test my abilities. Perhaps I could assist with updates and help make it an awesome project. Additionally, I have some personal thoughts on this project. Can you please provide me with a way to reach you personally?

2023-04-16 19:31 UTC, sanders41 requested changes
Because there are lines that weren't changed that will need updating I can't request the changes in the "normal" way so I am going to do a series of comments list out what needs to be done.

2023-04-16 19:31 UTC, sanders41 commented
In `_cache.py` the `add` and `get` methods of the `Cache` class both need to be updated as follows:

```py
    def add(
        self,
        *,
        cache_key: str,
        location: Location | None = None,
        current_weather: CurrentWeather | None = None,
        one_call_weather: OneCallWeather | None = None,
        cache_size: int = 5,
    ) -> None:
        def save_cache() -> None:
            cache: dict[str, Any] = {}
            location_cache = location.dict() if location else None
            current_weather_cache = (
                CurrentWeatherCache(
                    date_time_saved=datetime.utcnow(), current_weather=current_weather
                ).dict()
                if current_weather
                else None
            )
            one_call_weather_cache = (
                OneCallWeatherCache(
                    date_time_saved=datetime.utcnow(), one_call_weather=one_call_weather
                ).dict()
                if one_call_weather
                else None
            )

            cache_hit = self.get(cache_key)

            if cache_hit:
                cache[cache_key.lower()] = {
                    "location": cache_hit.location.dict()
                    if cache_hit.location and not location_cache
                    else location_cache,
                    "currentWeather": cache_hit.current_weather.dict()
                    if cache_hit.current_weather and not current_weather_cache
                    else current_weather_cache,
                    "oneCallWeather": cache_hit.one_call_weather.dict()
                    if cache_hit.one_call_weather and not one_call_weather_cache
                    else one_call_weather_cache,
                }
            else:
                cache[cache_key.lower()] = {
                    "location": location_cache,
                    "currentWeather": current_weather_cache,
                    "oneCallWeather": one_call_weather_cache,
                }

            if self._cache:
                for key in self._cache:
                    if key != cache_key:
                        saved_cache = self._cache[key]
                        cache[key] = saved_cache.dict()

            with open(self._cache_file, "w") as f:
                json.dump(cache, f, cls=DateTimeEncoder)

        if not self._cache or len(self._cache.keys()) < cache_size:
            save_cache()
        else:
            last_key = list(self._cache.keys())[-1]
            del self._cache[last_key]
            save_cache()
```

and

```py
    def get(self, cache_key: str) -> CacheItem | None:
        if not self._cache or not self._cache.get(cache_key):
            return None

        cache = self._cache[cache_key.lower()]
        if cache.current_weather:
            time_diff = datetime.utcnow() - cache.current_weather.date_time_saved
            if (time_diff.total_seconds() / 60) > cache.current_weather.cache_duration_minutes:
                cache.current_weather = None

        if cache.one_call_weather:
            time_diff = datetime.utcnow() - cache.one_call_weather.date_time_saved
            if (time_diff.total_seconds() / 60) > cache.one_call_weather.cache_duration_minutes:
                cache.one_call_weather = None

        return cache

    def _load(self) -> dict[str, CacheItem] | None:
        if not self._cache_file.exists():
            return None

        with open(self._cache_file, "r") as f:
            json_cache = json.load(f)

        return {k: CacheItem(**v) for k, v in json_cache.items()}
```

2023-04-16 19:40 UTC, sanders41 commented
In `_location.py`, `_built_url` should be renamed to `build_location_url`. We are going to end up calling this a bunch of times in different files. There is already an `lru_cache` on this function so performance wise this will be fine because it only needs to be built once.

Then [these lines](https://github.com/sanders41/weather-command/blob/0b6cfb1e2d44910236501f5b9920c24350a4d03f/weather_command/_location.py#L37-L42) will change to:

```py
    base_url = build_location_url(how, city_zip, state, country)
    cache_hit = cache.get(base_url)
    if cache_hit and cache_hit.location:
        return cache_hit.location
```

And [these lines](https://github.com/sanders41/weather-command/blob/0b6cfb1e2d44910236501f5b9920c24350a4d03f/weather_command/_location.py#L64-L65) become:

```py
 cache.add(cache_key=base_url, location=location)
```

2023-04-16 19:46 UTC, sanders41 commented
In `_builder.py` `build_location_url` needs to be imported from `_location.py`.

`_gather_current_weather` changes to:

```py
async def _gather_current_weather(
    how: str,
    city_zip: str,
    *,
    state_code: str | None,
    country_code: str | None,
    units: str,
) -> tuple[CurrentWeather, Location]:
    location_url = build_location_url(how, city_zip, state_code, country_code)
    cache = Cache()
    cache_hit = cache.get(location_url)
    if cache_hit:
        if cache_hit.location:
            location = cache_hit.location
        else:
            location = get_location_details(
                how=how, city_zip=city_zip, state=state_code, country=country_code
            )
        if cache_hit.current_weather:
            current_weather = cache_hit.current_weather.current_weather
            return cache_hit.current_weather.current_weather, location
        else:
            url = build_weather_url(
                forecast_type="current",
                units=units,
                lon=location.lon,
                lat=location.lat,
            )
            current_weather = await get_current_weather(url, how, city_zip, cache_key=location_url)
            return current_weather, location

    location = get_location_details(
        how=how, city_zip=city_zip, state=state_code, country=country_code
    )

    url = build_weather_url(
        forecast_type="current",
        units=units,
        lon=location.lon,
        lat=location.lat,
    )
    current_weather = await get_current_weather(url, how, city_zip, cache_key=location_url)

    return current_weather, location
```

And `_gather_one_call_weather` changes to

```py
async def _gather_one_call_weather(
    how: str,
    city_zip: str,
    *,
    state_code: str | None,
    country_code: str | None,
    units: str,
) -> tuple[OneCallWeather, Location]:
    location_url = build_location_url(how, city_zip, state_code, country_code)
    cache = Cache()
    cache_hit = cache.get(location_url)
    if cache_hit:
        if cache_hit.location:
            location = cache_hit.location
        else:
            location = get_location_details(
                how=how, city_zip=city_zip, state=state_code, country=country_code
            )
        if cache_hit.one_call_weather:
            return cache_hit.one_call_weather.one_call_weather, location
        else:
            url = build_weather_url(
                forecast_type="daily", units=units, lon=location.lon, lat=location.lat
            )
            weather = await get_one_call_weather(url, how, city_zip, location_url)
            return weather, location

    location = get_location_details(
        how=how, city_zip=city_zip, state=state_code, country=country_code
    )

    url = build_weather_url(forecast_type="daily", units=units, lon=location.lon, lat=location.lat)
    weather = await get_one_call_weather(url, how, city_zip, location_url)

    return weather, location
```

2023-04-16 19:50 UTC, sanders41 commented
In `_weather.py`

`get_current_weather` changes to

```py
@retry(stop=stop_after_attempt(5), wait=wait_fixed(0.5), reraise=True)
async def get_current_weather(url: str, cache_key: str) -> CurrentWeather:
    try:
        async with AsyncClient() as client:
            response = await client.get(url)

        response.raise_for_status()
    except HTTPStatusError as e:
        check_status_error(e, console)

    try:
        weather = CurrentWeather(**response.json())
    except ValidationError:
        _print_validation_error()

    cache = Cache()
    cache.add(cache_key=cache_key, current_weather=weather)
    return weather
```

and `get_one_call_weather` changes to

```py
@retry(stop=stop_after_attempt(5), wait=wait_fixed(0.5), reraise=True)
async def get_one_call_weather(url: str, cache_key: str) -> OneCallWeather:
    async with AsyncClient() as client:
        response = await client.get(url)
    try:
        response.raise_for_status()
    except HTTPStatusError as e:
        check_status_error(e, console)

    try:
        weather = OneCallWeather(**response.json())
    except ValidationError:
        _print_validation_error()

    cache = Cache()
    cache.add(cache_key=cache_key, one_call_weather=weather)

    return weather
```

2023-04-16 20:00 UTC, sanders41 commented
In `main.py` `build_location_url` needs to be imported from `_location.py`

`_preload_cache` needs to be updated to:

```py
async def _preload_cache(
    how: str,
    city_zip: str,
    state_code: Union[str, None],
    country_code: Union[str, None],
    units: str,
) -> None:
    with console.status("Getting weather..."):
        retrieve: List[Coroutine] = []
        location_url = build_location_url(how, city_zip, state_code, country_code)
        cache = Cache()
        cache_hit = cache.get(location_url)
        if cache_hit:
            if cache_hit.location:
                location = cache_hit.location
            else:  # pragma: no cover
                # This is a fail safe. It should only be possible to get here if someone manually
                # modified the cache file.
                location = get_location_details(
                    how="zip", city_zip=city_zip, state=state_code, country=country_code
                )

            if not cache_hit.current_weather:
                url = build_weather_url(
                    forecast_type="current",
                    units=units,
                    lon=location.lon,
                    lat=location.lat,
                )
                retrieve.append(get_current_weather(url, location_url))
            if not cache_hit.one_call_weather:
                url = build_weather_url(
                    forecast_type="daily", units=units, lon=location.lon, lat=location.lat
                )
                retrieve.append(get_one_call_weather(url, location_url))
        else:
            location = get_location_details(
                how="zip", city_zip=city_zip, state=state_code, country=country_code
            )

            url = build_weather_url(
                forecast_type="current", units=units, lon=location.lon, lat=location.lat
            )
            retrieve.append(get_current_weather(url, location_url))

            url = build_weather_url(
                forecast_type="daily", units=units, lon=location.lon, lat=location.lat
            )
            retrieve.append(get_one_call_weather(url, location_url))

        if retrieve:
            await asyncio.gather(*retrieve)
```

`_runner` gets updated to:

```py
async def _runner(
    how: str,
    city_zip: str,
    state_code: Union[str, None],
    country_code: Union[str, None],
    imperial: bool,
    am_pm: bool,
    forecast_type: ForecastType,
    temp_only: bool,
    pager: bool,
    clear_cache: bool,
    terminal_width: Union[int, None],
) -> None:
    settings = load_settings()

    if not imperial and settings.imperial is not None:
        units = "imperial" if settings.imperial else "metric"
    else:
        units = "imperial" if imperial else "metric"

    if not temp_only and settings.temp_only is not None:
        temp_only_choice = settings.temp_only
    else:
        temp_only_choice = temp_only

    if not am_pm and settings.am_pm is not None:
        am_pm_choice = settings.am_pm
    else:
        am_pm_choice = am_pm

    if clear_cache:
        cache = Cache()
        cache.clear()

    if not clear_cache:
        await _preload_cache(how, city_zip, state_code, country_code, units)

    if forecast_type == "current":
        await show_current(
            how=how,
            city_zip=city_zip,
            units=units,
            state_code=state_code,
            country_code=country_code,
            am_pm=am_pm_choice,
            temp_only=temp_only_choice,
            pager=pager,
            terminal_width=terminal_width,
        )
    elif forecast_type == "daily":
        await show_daily(
            how=how,
            city_zip=city_zip,
            units=units,
            state_code=state_code,
            country_code=country_code,
            am_pm=am_pm_choice,
            temp_only=temp_only_choice,
            pager=pager,
            terminal_width=terminal_width,
        )
    elif forecast_type == "hourly":
        await show_hourly(
            how=how,
            city_zip=city_zip,
            units=units,
            state_code=state_code,
            country_code=country_code,
            am_pm=am_pm_choice,
            temp_only=temp_only_choice,
            pager=pager,
            terminal_width=terminal_width,
        )
```

2023-04-16 20:02 UTC, sanders41 commented
For testing the https://github.com/sanders41/weather-command/blob/main/tests/assets/cache.json file needs to have the key updated and an additional record added. I'm just going to paste the whole updated file here that can be copy and pasted in, replacing the old data.

```json
{
  "https://nominatim.openstreetmap.org/search?format=json&limit=1&city=greensboro": {
    "location": {
      "display_name": "Greensboro, Guilford County, North Carolina, 27455, United States",
      "lat": 36.158075647227044,
      "lon": -79.81330895473118
    },
    "currentWeather": {
      "cache_duration_minutes": 15,
      "date_time_saved": "2021-12-22T01:36:38.212266",
      "current_weather": {
        "coord": { "lon": -79.8133, "lat": 36.1581 },
        "weather": [
          {
            "id": 804,
            "main": "Clouds",
            "description": "overcast clouds",
            "icon": "04n"
          }
        ],
        "base": "stations",
        "main": {
          "temp": 39.45,
          "feels_like": 39.45,
          "temp_min": 34.32,
          "temp_max": 43.23,
          "pressure": 1011,
          "humidity": 79
        },
        "visibility": 10000,
        "wind": { "speed": 1.99, "deg": 19, "gust": 3.0 },
        "clouds": { "all": 90 },
        "rain": null,
        "snow": null,
        "dt": "2021-12-22T01:36:38+00:00",
        "sys": {
          "type": 2,
          "id": 2034083,
          "country": "US",
          "sunrise": "2021-12-21T12:26:39+00:00",
          "sunset": "2021-12-21T22:08:18+00:00"
        },
        "timezone": -18000,
        "id": 4493990,
        "name": "Summerfield",
        "cod": 200
      }
    },
    "oneCallWeather": {
      "cache_duration_minutes": 15,
      "date_time_saved": "2021-12-22T01:36:52.676059",
      "one_call_weather": {
        "lat": 36.1581,
        "lon": -79.8133,
        "timezone": "America/New_York",
        "timezone_offset": -18000,
        "current": {
          "dt": 1640137012,
          "sunrise": "2021-12-21T12:26:39+00:00",
          "sunset": "2021-12-21T22:08:18+00:00",
          "temp": 39.45,
          "feels_like": 39.45,
          "pressure": 1011,
          "humidity": 79,
          "dew_point": 33.49,
          "uvi": 0.0,
          "clouds": 90,
          "visibility": 10000,
          "wind_speed": 1.99,
          "wind_deg": 19,
          "wind_gust": 3.0,
          "weather": [
            {
              "id": 804,
              "main": "Clouds",
              "description": "overcast clouds",
              "icon": "04n"
            }
          ]
        },
        "minutely": [
          { "dt": "2021-12-22T01:37:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T01:38:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T01:39:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T01:40:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T01:41:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T01:42:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T01:43:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T01:44:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T01:45:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T01:46:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T01:47:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T01:48:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T01:49:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T01:50:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T01:51:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T01:52:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T01:53:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T01:54:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T01:55:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T01:56:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T01:57:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T01:58:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T01:59:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:00:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:01:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:02:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:03:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:04:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:05:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:06:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:07:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:08:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:09:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:10:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:11:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:12:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:13:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:14:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:15:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:16:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:17:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:18:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:19:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:20:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:21:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:22:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:23:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:24:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:25:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:26:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:27:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:28:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:29:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:30:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:31:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:32:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:33:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:34:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:35:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:36:00+00:00", "precipitation": 0.0 },
          { "dt": "2021-12-22T02:37:00+00:00", "precipitation": 0.0 }
        ],
        "hourly": [
          {
            "dt": "2021-12-22T01:00:00+00:00",
            "temp": 39.22,
            "feels_like": 35.87,
            "pressure": 1011,
            "humidity": 75,
            "dew_point": 31.98,
            "uvi": 0.0,
            "weather": [
              {
                "id": 804,
                "main": "Clouds",
                "description": "overcast clouds",
                "icon": "04n"
              }
            ],
            "clouds": 92,
            "visibility": 10000,
            "wind_speed": 4.61,
            "wind_gust": 10.16,
            "wind_deg": 5,
            "rain": null,
            "snow": null,
            "pop": 0
          },
          {
            "dt": "2021-12-22T02:00:00+00:00",
            "temp": 39.45,
            "feels_like": 36.36,
            "pressure": 1011,
            "humidity": 79,
            "dew_point": 33.49,
            "uvi": 0.0,
            "weather": [
              {
                "id": 804,
                "main": "Clouds",
      [...]

2023-04-16 20:03 UTC, sanders41 commented
`test_main.py` needs two additional tests added:

```py
@pytest.mark.usefixtures("mock_cache_dir")
@patch("weather_command._cache.datetime")
def test_main_cache_hit(
    mock_dt,
    mock_location,
    mock_current_weather,
    mock_one_call_weather,
    test_runner,
    cache_with_file,
):
    mock_dt.utcnow = Mock(return_value=datetime(2021, 12, 22, 1, 36, 38))
    location = mock_location
    current_weather = mock_current_weather
    one_call_weather = mock_one_call_weather

    cache_key = "https://nominatim.openstreetmap.org/search?format=json&limit=1&postalcode=27455"

    cache_with_file.add(
        cache_key=cache_key,
        location=location,
        current_weather=current_weather,
        one_call_weather=one_call_weather,
    )
    args = ["zip", "27455", "--terminal-width", 180]
    result = test_runner.invoke(app, args, catch_exceptions=False)

    out = result.stdout

    assert "Greensboro" in out


@pytest.mark.usefixtures("mock_cache_dir_with_file")
def test_main_cache_hit_expired(
    mock_one_call_weather_response, mock_current_weather_response, test_runner, monkeypatch
):
    async def mock_get_weather_response(*args, **kwargs):
        if "onecall" in args[1]:
            return mock_one_call_weather_response

        return mock_current_weather_response

    monkeypatch.setattr(httpx.AsyncClient, "get", mock_get_weather_response)
    args = ["zip", "27455", "--terminal-width", 180]
    result = test_runner.invoke(app, args, catch_exceptions=False)

    out = result.stdout

    assert "Greensboro" in out
```

2023-04-16 20:05 UTC, sanders41 commented
After making these there are going to be a lot of tests that fail for various reason that need fixing. One of the main reason tests are going to fail is if it is using the old cache key of zip. In that case they will need to be updated to a key from the new testing cache.

2023-04-16 20:06 UTC, sanders41 commented
Honestly the best way to get in touch about the project is to open an issue, that makes it easy to find and track.

2023-04-20 09:00 UTC, sanders41 commented
I wanted to get this released so I went ahead and implemented it in #416

2023-04-20 09:00 UTC, closed without merging